import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import http from 'node:http';
import os from 'node:os';
import path from 'node:path';

import express, {
  type ErrorRequestHandler,
  type Express,
  type Request,
  type RequestHandler,
  type Response,
} from 'express';
import asyncHandler from 'express-async-handler';

import * as assets from './assets.js';
import { discoverInfoDirs } from './discover-info-dirs.js';
import {
  parseQuestionPreviewServerOptions,
  type QuestionPreviewServerOptions,
} from './question-preview-server-options.js';
import {
  type QuestionPreviewPayload,
  type QuestionPreviewRuntime,
  type QuestionPreviewRuntimeRenderInput,
  type QuestionPreviewRuntimeRenderOptions,
  type QuestionPreviewRuntimeOptions,
  createQuestionPreviewRuntime,
} from './question-preview-render.js';

const GENERATED_FILES_TEMP_PREFIX = 'pl-preview-server-generated-files-';
const GENERATED_FILES_OWNER_FILE = '.owner.json';
const activeGeneratedFilesRoots = new Set<string>();

export { parseQuestionPreviewServerOptions, type QuestionPreviewServerOptions };

export interface QuestionDiscoveryItem {
  previewUrl: string;
  qid: string;
  title: string;
  topic: string | null;
  type: string;
}

export interface StartedQuestionPreviewServer {
  close(): Promise<void>;
  generatedFilesRoot: string;
  options: QuestionPreviewServerOptions;
  runtime: QuestionPreviewRuntime;
  server: http.Server;
}

/**
 * Binds the HTTP server and resolves once the server is accepting requests.
 *
 * @param server - The Node HTTP server instance to start.
 * @param port - The TCP port to bind.
 * @param host - The host/interface to bind.
 */
function listen(server: http.Server, port: number, host: string) {
  return new Promise<void>((resolve, reject) => {
    server.once('error', reject);
    server.listen(port, host, () => {
      server.off('error', reject);
      resolve();
    });
  });
}

/**
 * Converts preview-server startup options into the runtime options required by
 * the question renderer.
 *
 * @param options - Validated preview-server options from CLI parsing.
 */
function makeRuntimeOptions(options: QuestionPreviewServerOptions): QuestionPreviewRuntimeOptions {
  return {
    cacheType: options.cacheType,
    courseDir: options.courseDir,
    devMode: options.devMode,
    prewarmWorkers: true,
    questionTimeoutMilliseconds: options.questionTimeoutMilliseconds,
    urlPrefix: '/preview-render',
    workersCount: options.workersCount,
    workersExecutionMode: options.workersExecutionMode,
  };
}

/**
 * Checks whether a process ID appears to still belong to a live process.
 *
 * @param pid - Process ID read from a generated-files owner record.
 */
function processIsAlive(pid: number) {
  if (!Number.isSafeInteger(pid) || pid <= 0) return false;

  try {
    process.kill(pid, 0);
    return true;
  } catch (err) {
    if (err instanceof Error && 'code' in err && err.code === 'ESRCH') return false;
    return true;
  }
}

/**
 * Reads the owner PID for a generated-files root, returning `null` when the
 * owner file is missing or malformed.
 *
 * @param root - Temporary generated-files directory to inspect.
 */
async function generatedFilesRootOwnerPid(root: string) {
  try {
    const owner = JSON.parse(
      await fs.readFile(path.join(root, GENERATED_FILES_OWNER_FILE), 'utf8'),
    ) as unknown;
    if (typeof owner !== 'object' || owner == null || Array.isArray(owner)) return null;
    const pid = (owner as Record<string, unknown>).pid;
    return typeof pid === 'number' ? pid : null;
  } catch {
    return null;
  }
}

/**
 * Removes generated-files temp directories whose owning preview server is no
 * longer running.
 */
async function cleanupStaleGeneratedFilesRoots() {
  let entries: { isDirectory(): boolean; name: string }[];
  try {
    entries = await fs.readdir(os.tmpdir(), { withFileTypes: true });
  } catch {
    return;
  }

  await Promise.all(
    entries.map(async (entry) => {
      if (!entry.isDirectory() || !entry.name.startsWith(GENERATED_FILES_TEMP_PREFIX)) return;

      const root = path.join(os.tmpdir(), entry.name);
      if (activeGeneratedFilesRoots.has(root)) return;

      const ownerPid = await generatedFilesRootOwnerPid(root);
      if (ownerPid != null && ownerPid !== process.pid && processIsAlive(ownerPid)) return;

      await fs.rm(root, { force: true, recursive: true }).catch(() => {});
    }),
  );
}

/**
 * Creates the root directory used to store files generated by preview renders.
 */
async function createGeneratedFilesRoot() {
  await cleanupStaleGeneratedFilesRoots();

  const root = await fs.mkdtemp(path.join(os.tmpdir(), GENERATED_FILES_TEMP_PREFIX));
  activeGeneratedFilesRoots.add(root);
  await fs.writeFile(
    path.join(root, GENERATED_FILES_OWNER_FILE),
    JSON.stringify({ createdAt: new Date().toISOString(), pid: process.pid }),
  );
  return root;
}

/**
 * Removes a generated-files root owned by this preview-server instance.
 *
 * @param root - Temporary generated-files directory to delete.
 */
async function removeGeneratedFilesRoot(root: string) {
  activeGeneratedFilesRoots.delete(root);
  await fs.rm(root, { force: true, recursive: true }).catch(() => {});
}

/**
 * Wraps a preview runtime so infrastructure failures discard the current
 * runtime and allow a later request to create a fresh one.
 */
class ReplaceableQuestionPreviewRuntime implements QuestionPreviewRuntime {
  private currentRuntime: QuestionPreviewRuntime | null;
  private nextRuntimePromise: Promise<QuestionPreviewRuntime> | null = null;

  /**
   * @param initialRuntime - Runtime created during preview-server startup.
   * @param createRuntime - Factory used to create replacement runtimes.
   * @param runtimeOptions - Options passed to `createRuntime` for replacements.
   */
  constructor(
    initialRuntime: QuestionPreviewRuntime,
    private readonly createRuntime: (
      options: QuestionPreviewRuntimeOptions,
    ) => Promise<QuestionPreviewRuntime>,
    private readonly runtimeOptions: QuestionPreviewRuntimeOptions,
  ) {
    this.currentRuntime = initialRuntime;
  }

  /**
   * Returns the current runtime, creating a replacement if a previous request
   * discarded it after a failure.
   */
  private async getRuntime() {
    if (this.currentRuntime != null) return this.currentRuntime;

    this.nextRuntimePromise ??= this.createRuntime(this.runtimeOptions).finally(() => {
      this.nextRuntimePromise = null;
    });
    this.currentRuntime = await this.nextRuntimePromise;
    return this.currentRuntime;
  }

  /**
   * Marks a failed runtime as unusable and closes it.
   *
   * @param runtime - The runtime instance that failed during rendering.
   */
  private async discardRuntime(runtime: QuestionPreviewRuntime) {
    if (this.currentRuntime !== runtime) return;
    this.currentRuntime = null;

    try {
      await runtime.close();
    } catch {
      // The runtime has already failed. A close failure should not prevent
      // the request from reporting the original infrastructure failure.
    }
  }

  /**
   * Renders through the active runtime and discards that runtime if rendering
   * fails at the infrastructure layer.
   *
   * @param input - Question and variant information for the render.
   * @param options - Optional render settings, including generated-file output.
   */
  async render(
    input: QuestionPreviewRuntimeRenderInput,
    options?: QuestionPreviewRuntimeRenderOptions,
  ) {
    const runtime = await this.getRuntime();

    try {
      return await runtime.render(input, options);
    } catch (err) {
      await this.discardRuntime(runtime);
      throw err;
    }
  }

  /**
   * Closes the current or pending runtime during preview-server shutdown.
   */
  async close() {
    const pendingRuntime = this.nextRuntimePromise;
    if (pendingRuntime != null) {
      await pendingRuntime.catch(() => null);
    }

    const runtime = this.currentRuntime;
    this.currentRuntime = null;
    await runtime?.close();
  }
}

/**
 * Renders a generic preview error document without exposing internal render
 * details.
 */
function renderPreviewErrorDocument() {
  return `<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Question Preview Error</title>
</head>
<body>
<main>
<h1>Question preview failed</h1>
<p>Check the preview server console for details.</p>
</main>
</body>
</html>`;
}

/**
 * Decodes a route suffix into safe path segments for bounded asset lookup.
 *
 * @param encodedPath - URL-encoded route suffix after the asset-route prefix.
 */
function decodeAssetPathSegments(encodedPath: string) {
  if (encodedPath.length === 0) return null;

  const segments = encodedPath.split('/');
  if (segments.length === 0) return null;

  const decodedSegments: string[] = [];
  for (const segment of segments) {
    let decoded: string;
    try {
      decoded = decodeURIComponent(segment);
    } catch {
      return null;
    }

    if (
      decoded.length === 0 ||
      decoded === '.' ||
      decoded === '..' ||
      decoded.includes('\0') ||
      decoded.includes('/') ||
      decoded.includes('\\') ||
      path.isAbsolute(decoded)
    ) {
      return null;
    }

    decodedSegments.push(decoded);
  }

  return decodedSegments;
}

/**
 * Checks whether a resolved file path stays within an allowed root.
 *
 * @param root - Absolute or relative root directory for the allowed tree.
 * @param filePath - Candidate absolute file path to validate.
 */
function isPathInsideRoot(root: string, filePath: string) {
  const relativePath = path.relative(root, filePath);
  return (
    relativePath.length === 0 || (!relativePath.startsWith('..') && !path.isAbsolute(relativePath))
  );
}

/**
 * Resolves a file below a root while rejecting traversal, missing files,
 * directories, and symlinks along the path.
 *
 * @param rootInput - Directory that bounds the allowed file lookup.
 * @param pathSegments - Already-decoded path segments relative to `rootInput`.
 */
async function resolveBoundedFile(rootInput: string, pathSegments: string[]) {
  const root = path.resolve(rootInput);
  const filePath = path.resolve(root, ...pathSegments);
  if (!isPathInsideRoot(root, filePath)) return null;

  let currentPath = root;
  const rootStat = await fs.lstat(currentPath);
  if (rootStat.isSymbolicLink() || !rootStat.isDirectory()) return null;

  let fileStat = rootStat;
  for (const segment of pathSegments) {
    currentPath = path.join(currentPath, segment);
    fileStat = await fs.lstat(currentPath);
    if (fileStat.isSymbolicLink()) return null;
  }

  if (!fileStat.isFile()) return null;
  return filePath;
}

/**
 * Searches multiple bounded roots for the first existing safe file.
 *
 * @param roots - Candidate root directories to search in order.
 * @param pathSegments - Already-decoded path segments relative to each root.
 */
async function resolveBoundedFileFromRoots(roots: string[], pathSegments: string[]) {
  for (const root of roots) {
    try {
      const filePath = await resolveBoundedFile(root, pathSegments);
      if (filePath != null) return filePath;
    } catch (err) {
      if (err instanceof Error && 'code' in err && err.code === 'ENOENT') continue;
      throw err;
    }
  }

  return null;
}

/**
 * Validates the render ID segment used to scope generated preview files.
 *
 * @param renderId - URL path segment expected to contain a UUID render ID.
 */
function isGeneratedFilesRenderId(renderId: string) {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(
    renderId,
  );
}

interface BoundedAssetRequest {
  roots: string[];
  segments: string[];
}

const GENERATED_FILES_ROUTE_PREFIX = '/preview-render/generatedFilesQuestion/render/';
const GENERATED_FILES_ROUTE_PATTERN = `${GENERATED_FILES_ROUTE_PREFIX}*`;

/**
 * Converts a generated-files URL into a bounded file lookup request.
 *
 * @param generatedFilesRoot - Temp root that contains render-ID directories.
 * @param pathname - Raw request pathname without query string.
 */
function generatedFilesAssetRequestFromPathname(
  generatedFilesRoot: string,
  pathname: string,
): BoundedAssetRequest | null {
  const segments = decodeAssetPathSegments(pathname.slice(GENERATED_FILES_ROUTE_PREFIX.length));
  if (segments == null || segments.length < 2) return null;

  const [renderId, ...fileSegments] = segments;
  if (!isGeneratedFilesRenderId(renderId)) return null;

  return {
    roots: [path.join(generatedFilesRoot, renderId)],
    segments: fileSegments,
  };
}

/**
 * Converts a startup-course asset URL into a bounded file lookup request.
 *
 * @param courseDir - Course directory supplied at preview-server startup.
 * @param pathname - Raw request pathname without query string.
 */
function startupCourseAssetRequestFromPathname(
  courseDir: string,
  pathname: string,
): BoundedAssetRequest | null {
  const startupCourseAssetRoutes = [
    {
      prefix: '/preview-render/clientFilesCourse/',
      roots: [path.join(courseDir, 'clientFilesCourse')],
      stripCachebuster: false,
    },
    {
      prefix: '/preview-render/elements/',
      roots: [path.join(courseDir, 'elements')],
      stripCachebuster: false,
    },
    {
      prefix: '/preview-render/cacheableElements/',
      roots: [path.join(courseDir, 'elements')],
      stripCachebuster: true,
    },
    {
      prefix: '/preview-render/elementExtensions/',
      roots: [path.join(courseDir, 'elementExtensions')],
      stripCachebuster: false,
    },
    {
      prefix: '/preview-render/cacheableElementExtensions/',
      roots: [path.join(courseDir, 'elementExtensions')],
      stripCachebuster: true,
    },
  ];

  for (const route of startupCourseAssetRoutes) {
    if (!pathname.startsWith(route.prefix)) continue;

    const segments = decodeAssetPathSegments(pathname.slice(route.prefix.length));
    if (segments == null) return null;

    const fileSegments = route.stripCachebuster ? segments.slice(1) : segments;
    if (fileSegments.length === 0) return null;

    return {
      roots: route.roots,
      segments: fileSegments,
    };
  }

  const questionFilesPrefix = '/preview-render/questions/';
  if (pathname.startsWith(questionFilesPrefix)) {
    const segments = decodeAssetPathSegments(pathname.slice(questionFilesPrefix.length));
    if (segments == null) return null;

    const filesSegmentIndex = segments.lastIndexOf('files');
    if (filesSegmentIndex <= 0 || filesSegmentIndex === segments.length - 1) return null;

    const qidSegments = segments.slice(0, filesSegmentIndex);
    const fileSegments = segments.slice(filesSegmentIndex + 1);

    return {
      roots: [path.join(courseDir, 'questions', ...qidSegments, 'clientFilesQuestion')],
      segments: fileSegments,
    };
  }

  return null;
}

/**
 * Reads the URL pathname exactly as sent by the client, before Express decodes
 * wildcard route parameters.
 *
 * @param req - Incoming HTTP request.
 */
function rawRequestPathname(req: http.IncomingMessage) {
  const rawUrl = req.url ?? '/';
  const queryStart = rawUrl.search(/[?#]/);
  return queryStart === -1 ? rawUrl : rawUrl.slice(0, queryStart);
}

/**
 * Extracts a valid HTTP status code from framework errors.
 *
 * @param err - Unknown error thrown while handling a request.
 */
function errorStatusCode(err: unknown) {
  if (typeof err !== 'object' || err == null || Array.isArray(err)) return null;
  const status = (err as Record<string, unknown>).status;
  return Number.isInteger(status) && (status as number) >= 400 && (status as number) < 600
    ? (status as number)
    : null;
}

/**
 * Sends a bounded asset response or a 404 when the requested file is invalid or
 * missing.
 *
 * @param res - Express response used for `sendFile`.
 * @param assetRequest - Safe root and path-segment lookup request, or `null`.
 */
async function handleBoundedAssetRequest(res: Response, assetRequest: BoundedAssetRequest | null) {
  if (assetRequest == null) {
    res.status(404).end();
    return;
  }

  const filePath = await resolveBoundedFileFromRoots(assetRequest.roots, assetRequest.segments);
  if (filePath == null) {
    res.status(404).end();
    return;
  }

  await new Promise<void>((resolve, reject) => {
    res.sendFile(filePath, { headers: { 'cache-control': 'no-store' } }, (err) => {
      if (err) {
        reject(err);
        return;
      }
      resolve();
    });
  });
}

const STARTUP_COURSE_ASSET_ROUTE_PATTERNS = [
  '/preview-render/clientFilesCourse/*',
  '/preview-render/elements/*',
  '/preview-render/cacheableElements/*',
  '/preview-render/elementExtensions/*',
  '/preview-render/cacheableElementExtensions/*',
  '/preview-render/questions/*',
];

/**
 * Registers Express routes for startup-course assets.
 *
 * @param app - Express application receiving the routes.
 * @param options - Preview-server options, including `courseDir`.
 */
function registerStartupCourseAssetRoutes(app: Express, options: QuestionPreviewServerOptions) {
  for (const routePattern of STARTUP_COURSE_ASSET_ROUTE_PATTERNS) {
    app
      .route(routePattern)
      .get(
        asyncHandler(async (req, res) => {
          await handleBoundedAssetRequest(
            res,
            startupCourseAssetRequestFromPathname(options.courseDir, rawRequestPathname(req)),
          );
        }),
      )
      .all((_req, res) => {
        res.status(405).end();
      });
  }
}

/**
 * Registers Express routes for generated preview files.
 *
 * @param app - Express application receiving the routes.
 * @param generatedFilesRoot - Temp root containing render-ID directories.
 */
function registerGeneratedFilesAssetRoutes(app: Express, generatedFilesRoot: string) {
  app
    .route(GENERATED_FILES_ROUTE_PATTERN)
    .get(
      asyncHandler(async (req, res) => {
        await handleBoundedAssetRequest(
          res,
          generatedFilesAssetRequestFromPathname(generatedFilesRoot, rawRequestPathname(req)),
        );
      }),
    )
    .all((_req, res) => {
      res.status(405).end();
    });
}

/**
 * Wraps rendered question fragments in a full HTML document for the browser.
 *
 * @param payload - Rendered question HTML fragments from the preview runtime.
 */
function renderPreviewDocument(payload: QuestionPreviewPayload) {
  return `<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
${payload.headHtml}
</head>
<body>
${payload.bodyHtml}
</body>
</html>`;
}

/**
 * Logs render failure details that are no longer exposed in browser responses.
 *
 * @param details - Renderer failure details for the failed preview.
 */
function logPreviewRenderFailureDetails(details: unknown) {
  console.error('Question preview render failed:', details);
}

/**
 * Checks whether a qid would escape or confuse the course question namespace.
 *
 * @param qid - Decoded question ID from the request path.
 */
function invalidQuestionPreviewQid(qid: string) {
  const segments = qid.split('/');

  return (
    qid.length === 0 ||
    qid.startsWith('/') ||
    qid.includes('\\') ||
    qid.includes('\0') ||
    path.isAbsolute(qid) ||
    segments.some((segment) => segment.length === 0 || segment === '.' || segment === '..')
  );
}

/**
 * Builds the default direct-preview URL for a question ID.
 *
 * @param qid - Course-relative question ID.
 */
function previewUrlForQid(qid: string) {
  return `/questions/${qid.split('/').map(encodeURIComponent).join('/')}?variant=1`;
}

/**
 * Converts parsed `info.json` metadata into a discovery API item.
 *
 * @param qid - Course-relative question ID.
 * @param info - Parsed `info.json` object for the question.
 */
function questionDiscoveryItem(qid: string, info: Record<string, unknown>): QuestionDiscoveryItem {
  if (
    typeof info.title !== 'string' ||
    typeof info.topic !== 'string' ||
    typeof info.type !== 'string'
  ) {
    throw new Error('Expected info.json to contain string title, topic, and type fields.');
  }

  return {
    previewUrl: previewUrlForQid(qid),
    qid,
    title: info.title,
    topic: info.topic,
    type: info.type,
  };
}

/**
 * Builds a discovery item for a question with invalid or unreadable metadata.
 *
 * @param qid - Course-relative question ID.
 */
function invalidQuestionDiscoveryItem(qid: string): QuestionDiscoveryItem {
  return {
    previewUrl: previewUrlForQid(qid),
    qid,
    title: qid,
    topic: null,
    type: 'invalid-info-json',
  };
}

/**
 * Lists questions in a course for the preview discovery API.
 *
 * @param courseDir - Course directory supplied at preview-server startup.
 */
export async function listQuestionDiscoveryItems(
  courseDir: string,
): Promise<QuestionDiscoveryItem[]> {
  const questionsRoot = path.join(courseDir, 'questions');
  const qids = await discoverInfoDirs(questionsRoot, 'info.json');
  const questions = await Promise.all(
    qids.map(async (qidPath) => {
      const qid = qidPath.split(path.sep).join('/');
      const infoPath = path.join(questionsRoot, qidPath, 'info.json');
      try {
        const info = JSON.parse(await fs.readFile(infoPath, 'utf8')) as unknown;
        if (typeof info !== 'object' || info == null || Array.isArray(info)) {
          throw new Error('Expected info.json to contain an object.');
        }
        return questionDiscoveryItem(qid, info as Record<string, unknown>);
      } catch {
        return invalidQuestionDiscoveryItem(qid);
      }
    }),
  );
  return questions.sort((a, b) => a.qid.localeCompare(b.qid));
}

/**
 * Adds discovery API CORS headers to allowed discovery requests.
 *
 * @param options - Preview-server options containing allowed CORS origins.
 */
function discoveryCorsMiddleware(options: QuestionPreviewServerOptions): RequestHandler {
  return (req, res, next) => {
    const origin = req.get('origin');
    if (origin != null && options.corsOrigins.includes(origin)) {
      res.set('access-control-allow-origin', origin);
      res.vary('Origin');
    }

    next();
  };
}

/**
 * Handles CORS preflight requests for the question discovery API.
 *
 * @param params - Discovery preflight inputs.
 * @param params.req - Incoming preflight request.
 * @param params.res - Express response object.
 */
function handleQuestionDiscoveryPreflight(params: { req: Request; res: Response }) {
  const { req, res } = params;

  const requestHeaders = req.get('access-control-request-headers');
  res.status(204).set('access-control-allow-methods', 'GET, OPTIONS');
  if (requestHeaders != null) {
    res.set('access-control-allow-headers', requestHeaders);
  }
  res.end();
}

/**
 * Handles discovery API GET requests by returning the startup course question
 * list.
 *
 * @param params - Discovery GET inputs.
 * @param params.options - Preview-server options, including `courseDir`.
 * @param params.res - Express response object.
 */
async function handleQuestionDiscoveryGet(params: {
  options: QuestionPreviewServerOptions;
  res: Response;
}) {
  const { options, res } = params;

  res.status(200).json(await listQuestionDiscoveryItems(options.courseDir));
}

/**
 * Sends a CORS-aware 405 response for unsupported discovery API methods.
 *
 * @param params - Discovery method-not-allowed inputs.
 * @param params.res - Express response object.
 */
function handleQuestionDiscoveryMethodNotAllowed(params: { res: Response }) {
  const { res } = params;

  res.status(405).json({ error: 'Method not allowed' });
}

/**
 * Handles direct question preview URLs and renders the requested question.
 *
 * @param params - Direct preview request inputs.
 * @param params.generatedFilesRoot - Temp root for files produced by the render.
 * @param params.options - Preview-server options, including host, port, and course.
 * @param params.req - Incoming preview request.
 * @param params.res - Express response object.
 * @param params.runtime - Runtime used to render the question.
 */
async function handleQuestionPreviewRequest(params: {
  generatedFilesRoot: string;
  options: QuestionPreviewServerOptions;
  qid: string;
  req: Request;
  res: Response;
  runtime: QuestionPreviewRuntime;
}) {
  const { generatedFilesRoot, options, qid, req, res, runtime } = params;

  const url = new URL(req.url ?? '/', `http://${options.host}:${options.port}`);
  if (invalidQuestionPreviewQid(qid)) {
    res.status(422).type('html').send(renderPreviewErrorDocument());
    return;
  }

  if (!url.searchParams.has('variant')) {
    url.searchParams.set('variant', '1');
    res.redirect(302, `${req.path}${url.search}`);
    return;
  }

  const renderId = crypto.randomUUID();
  const result = await runtime.render(
    {
      qid,
      variantSeed: url.searchParams.get('variant') ?? '1',
    },
    {
      generatedFiles: {
        renderId,
        root: generatedFilesRoot,
      },
    },
  );

  if (result.ok) {
    res.status(200).type('html').send(renderPreviewDocument(result.payload));
    return;
  }

  logPreviewRenderFailureDetails(result.diagnostics);
  res.status(422).type('html').send(renderPreviewErrorDocument());
}

/**
 * Converts route handling failures into generic browser error pages.
 */
function questionPreviewErrorHandler(): ErrorRequestHandler {
  return (err, _req, res, next) => {
    if (res.headersSent) {
      next(err);
      return;
    }

    const status = errorStatusCode(err);
    if (status != null && status < 500) {
      res.status(status).end();
      return;
    }

    console.error('Question preview request failed:', err);
    res.status(500).type('html').send(renderPreviewErrorDocument());
  };
}

/**
 * Creates the Express app that serves direct previews, discovery API responses,
 * core assets, course assets, and generated files.
 *
 * @param params - Express app dependencies.
 * @param params.generatedFilesRoot - Temp root for generated preview files.
 * @param params.options - Validated preview-server options.
 * @param params.runtime - Runtime used by direct preview routes.
 */
function createQuestionPreviewApp(params: {
  generatedFilesRoot: string;
  options: QuestionPreviewServerOptions;
  runtime: QuestionPreviewRuntime;
}) {
  const { generatedFilesRoot, options, runtime } = params;

  const app = express();
  app.disable('x-powered-by');
  app.enable('strict routing');

  assets.applyMiddleware(app);

  app.use((_req, res, next) => {
    res.set('cache-control', 'no-store');
    next();
  });

  app.get(
    '/questions/*',
    asyncHandler(async (req, res) => {
      const qid = req.params[0];
      if (qid == null || qid.length === 0) {
        res.status(404).end();
        return;
      }

      await handleQuestionPreviewRequest({ generatedFilesRoot, options, qid, req, res, runtime });
    }),
  );

  app
    .route('/api/questions')
    .all(discoveryCorsMiddleware(options))
    .options((req, res) => {
      handleQuestionDiscoveryPreflight({ req, res });
    })
    .get(
      asyncHandler(async (req, res) => {
        await handleQuestionDiscoveryGet({ options, res });
      }),
    )
    .all((_req, res) => {
      handleQuestionDiscoveryMethodNotAllowed({ res });
    });

  registerStartupCourseAssetRoutes(app, options);
  registerGeneratedFilesAssetRoutes(app, generatedFilesRoot);

  app.use((_req, res) => {
    res.status(404).end();
  });

  app.use(questionPreviewErrorHandler());

  return app;
}

/**
 * Parses options, creates the preview runtime, starts the HTTP server, and
 * returns a handle that can cleanly close everything it owns.
 *
 * @param params - Startup dependencies and overrides.
 * @param params.argv - CLI-style arguments to parse; defaults to `process.argv`.
 * @param params.createRuntime - Runtime factory, injectable for tests.
 * @param params.onReady - Optional callback invoked after the server is bound.
 */
export async function startQuestionPreviewServer(
  params: {
    argv?: string[];
    createRuntime?: (options: QuestionPreviewRuntimeOptions) => Promise<QuestionPreviewRuntime>;
    onReady?: (started: StartedQuestionPreviewServer) => void;
  } = {},
): Promise<StartedQuestionPreviewServer> {
  const {
    argv = process.argv.slice(2),
    createRuntime = createQuestionPreviewRuntime,
    onReady,
  } = params;

  const options = await parseQuestionPreviewServerOptions(argv);
  const generatedFilesRoot = await createGeneratedFilesRoot();
  const runtimeOptions = makeRuntimeOptions(options);
  let runtime: ReplaceableQuestionPreviewRuntime | null = null;
  let server: http.Server | null = null;

  try {
    const previewRuntime = new ReplaceableQuestionPreviewRuntime(
      await createRuntime(runtimeOptions),
      createRuntime,
      runtimeOptions,
    );
    runtime = previewRuntime;
    await assets.init();
    server = http.createServer(
      createQuestionPreviewApp({
        generatedFilesRoot,
        options,
        runtime: previewRuntime,
      }),
    );

    await listen(server, options.port, options.host);
  } catch (err) {
    await runtime?.close().catch(() => {});
    const failedServer = server;
    if (failedServer != null) {
      await new Promise<void>((resolve) => failedServer.close(() => resolve()));
    }
    await removeGeneratedFilesRoot(generatedFilesRoot);
    throw err;
  }
  if (runtime == null || server == null) {
    await removeGeneratedFilesRoot(generatedFilesRoot);
    throw new Error('Preview server startup failed before runtime initialization.');
  }

  const startedRuntime = runtime;
  const startedServer = server;

  const started: StartedQuestionPreviewServer = {
    async close() {
      let closeError: unknown;
      try {
        await new Promise<void>((resolve, reject) => {
          startedServer.close((err) => (err ? reject(err) : resolve()));
        });
      } catch (err) {
        closeError = err;
      }

      try {
        await startedRuntime.close();
      } catch (err) {
        closeError ??= err;
      }

      await removeGeneratedFilesRoot(generatedFilesRoot);

      if (closeError != null) throw closeError;
    },
    generatedFilesRoot,
    options,
    runtime: startedRuntime,
    server: startedServer,
  };
  onReady?.(started);
  return started;
}
